name = "cluster-spmi-lldikti4"
type = "javascript"

account_id = "b23930131f25169fd1282bbd0cbe6586"
workers_dev = true
route = "https://cluster-spmi-lldikti4.laresarianti23.workers.dev/"
zone_id = "laresarianti23.workers.dev"

[site]
bucket = "./frontend"
entry-point = "workers-site"
